/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedLookupRouteImport } from './routes/_authenticated/lookup'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedIpoRouteImport } from './routes/_authenticated/ipo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedApplicationsTrademarkRouteImport } from './routes/_authenticated/applications.trademark'
import { Route as AuthenticatedApplicationsNtnRouteImport } from './routes/_authenticated/applications.ntn'
import { Route as AuthenticatedApplicationsCopyrightRouteImport } from './routes/_authenticated/applications.copyright'
import { Route as AuthenticatedApplicationsCompanyRouteImport } from './routes/_authenticated/applications.company'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLookupRoute = AuthenticatedLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpoRoute = AuthenticatedIpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsTrademarkRoute =
  AuthenticatedApplicationsTrademarkRouteImport.update({
    id: '/applications/trademark',
    path: '/applications/trademark',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsNtnRoute =
  AuthenticatedApplicationsNtnRouteImport.update({
    id: '/applications/ntn',
    path: '/applications/ntn',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsCopyrightRoute =
  AuthenticatedApplicationsCopyrightRouteImport.update({
    id: '/applications/copyright',
    path: '/applications/copyright',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsCompanyRoute =
  AuthenticatedApplicationsCompanyRouteImport.update({
    id: '/applications/company',
    path: '/applications/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ipo': typeof AuthenticatedIpoRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/lookup': typeof AuthenticatedLookupRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/applications/company': typeof AuthenticatedApplicationsCompanyRoute
  '/applications/copyright': typeof AuthenticatedApplicationsCopyrightRoute
  '/applications/ntn': typeof AuthenticatedApplicationsNtnRoute
  '/applications/trademark': typeof AuthenticatedApplicationsTrademarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ipo': typeof AuthenticatedIpoRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/lookup': typeof AuthenticatedLookupRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/applications/company': typeof AuthenticatedApplicationsCompanyRoute
  '/applications/copyright': typeof AuthenticatedApplicationsCopyrightRoute
  '/applications/ntn': typeof AuthenticatedApplicationsNtnRoute
  '/applications/trademark': typeof AuthenticatedApplicationsTrademarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ipo': typeof AuthenticatedIpoRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/lookup': typeof AuthenticatedLookupRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/applications/company': typeof AuthenticatedApplicationsCompanyRoute
  '/_authenticated/applications/copyright': typeof AuthenticatedApplicationsCopyrightRoute
  '/_authenticated/applications/ntn': typeof AuthenticatedApplicationsNtnRoute
  '/_authenticated/applications/trademark': typeof AuthenticatedApplicationsTrademarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/agents'
    | '/assignments'
    | '/clients'
    | '/dashboard'
    | '/ipo'
    | '/journal'
    | '/lookup'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/applications/$id'
    | '/applications/company'
    | '/applications/copyright'
    | '/applications/ntn'
    | '/applications/trademark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/agents'
    | '/assignments'
    | '/clients'
    | '/dashboard'
    | '/ipo'
    | '/journal'
    | '/lookup'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/applications/$id'
    | '/applications/company'
    | '/applications/copyright'
    | '/applications/ntn'
    | '/applications/trademark'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/agents'
    | '/_authenticated/assignments'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/ipo'
    | '/_authenticated/journal'
    | '/_authenticated/lookup'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/applications/$id'
    | '/_authenticated/applications/company'
    | '/_authenticated/applications/copyright'
    | '/_authenticated/applications/ntn'
    | '/_authenticated/applications/trademark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lookup': {
      id: '/_authenticated/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof AuthenticatedLookupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipo': {
      id: '/_authenticated/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof AuthenticatedIpoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/trademark': {
      id: '/_authenticated/applications/trademark'
      path: '/applications/trademark'
      fullPath: '/applications/trademark'
      preLoaderRoute: typeof AuthenticatedApplicationsTrademarkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/ntn': {
      id: '/_authenticated/applications/ntn'
      path: '/applications/ntn'
      fullPath: '/applications/ntn'
      preLoaderRoute: typeof AuthenticatedApplicationsNtnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/copyright': {
      id: '/_authenticated/applications/copyright'
      path: '/applications/copyright'
      fullPath: '/applications/copyright'
      preLoaderRoute: typeof AuthenticatedApplicationsCopyrightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/company': {
      id: '/_authenticated/applications/company'
      path: '/applications/company'
      fullPath: '/applications/company'
      preLoaderRoute: typeof AuthenticatedApplicationsCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIpoRoute: typeof AuthenticatedIpoRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLookupRoute: typeof AuthenticatedLookupRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
  AuthenticatedApplicationsCompanyRoute: typeof AuthenticatedApplicationsCompanyRoute
  AuthenticatedApplicationsCopyrightRoute: typeof AuthenticatedApplicationsCopyrightRoute
  AuthenticatedApplicationsNtnRoute: typeof AuthenticatedApplicationsNtnRoute
  AuthenticatedApplicationsTrademarkRoute: typeof AuthenticatedApplicationsTrademarkRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIpoRoute: AuthenticatedIpoRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLookupRoute: AuthenticatedLookupRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  AuthenticatedApplicationsCompanyRoute: AuthenticatedApplicationsCompanyRoute,
  AuthenticatedApplicationsCopyrightRoute:
    AuthenticatedApplicationsCopyrightRoute,
  AuthenticatedApplicationsNtnRoute: AuthenticatedApplicationsNtnRoute,
  AuthenticatedApplicationsTrademarkRoute:
    AuthenticatedApplicationsTrademarkRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
